namespace CefSharpDemo.Logic
{
    public enum ControlTypeEnum
    {
        Label = 0,
        TextBox = 1,
        DropDownList = 2,
        AutoCompleteDropDownList = 3,
        AssignControl = 4,
        CheckBox = 5,
        NumericTextBox = 6,
        DatePicker = 7,
        Grid = 8,
        NestedLink = 9,
        RadioButtonList = 10,
        CheckBoxList = 11,
        SearchPanel = 12,
        FileAttachment = 13,
        UserSignature = 14,
        Time = 15,
        Button = 16,
        TabControl = 17,
        ImageViewer = 18,
        ImageControl = 19,
        Payment = 20,
        Chart = 21,
        Gauge = 22,
        Tree = 23,
        GanttChart = 24,
        UserPicture = 25,
        GenericGrid = 26,
        RichTextBox = 27,
        Map = 28,
        Rectangle = 29,
        TabPage = 30,
        Line = 31,
        KPI = 32,
        State = 34,
        ClientChart = 35,
        DynamicImage = 36,
        Help = 37,
        AdvancedGantt = 38,
        Row = 39,
        Column = 40,
        Comment = 41,
        DateTimePicker = 42,
        CanvasPanel = 43,
        None = 44
    }
}
